# Generated by Django 4.1.2 on 2023-11-04 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Asana Name')),
                ('no_of_postures', models.PositiveIntegerField(verbose_name='Number of Postures')),
                ('created_at', models.DateTimeField(verbose_name='Created At')),
                ('last_modified_at', models.DateTimeField(verbose_name='Last Modified At')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_asans', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='Posture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.PositiveIntegerField(verbose_name='Step No')),
                ('name', models.CharField(max_length=100, verbose_name='Posture Name')),
                ('dataset', models.FileField(blank=True, null=True, upload_to='')),
                ('snap_shot', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Snap Shot')),
                ('last_modified_at', models.DateTimeField(null=True, verbose_name='Last Modified At')),
                ('first_trained_at', models.DateTimeField(null=True, verbose_name='First Trained At')),
                ('is_active', models.BooleanField(default=True)),
                ('asana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_postures', to='xraymodel.asana')),
            ],
        ),
    ]
